//! Copy reef-template into cargo-reef's source tree so it can be embedded
//! via `include_dir!` in src/main.rs.
//!
//! Source: ../reef-template/  (sibling repo in dev — the source of truth)
//! Dest:   ./template/         (vendored copy, gitignored, regenerated on each build)
//!
//! Filters out target/, .git/, Cargo.lock, dist/, node_modules/, .DS_Store —
//! anything that's a build artifact or should be regenerated by the user.
//!
//! For published builds (no ../reef-template available), assumes template/ has
//! already been populated (e.g., by a cargo-publish pre-step).

use std::path::Path;

fn main() {
    let src = Path::new("../reef-template");
    let dst = Path::new("template");

    if !src.exists() {
        if !dst.exists() {
            panic!(
                "Neither ../reef-template/ nor template/ exists. \
                 In dev: clone reef-template as a sibling. \
                 For published builds: ensure template/ was vendored before cargo publish."
            );
        }
        // Vendored (e.g. cargo publish output) — no copy needed
        println!("cargo:warning=cargo-reef build: using pre-vendored template/ (no ../reef-template found)");
        return;
    }

    println!("cargo:rerun-if-changed=../reef-template");

    if dst.exists() {
        std::fs::remove_dir_all(dst).expect("removing existing template/");
    }
    copy_filtered(src, dst);
}

fn copy_filtered(src: &Path, dst: &Path) {
    std::fs::create_dir_all(dst).expect("creating dst dir");

    for entry in std::fs::read_dir(src).expect("read_dir") {
        let entry = entry.expect("dir entry");
        let name = entry.file_name();
        let name_str = name.to_string_lossy();

        // Skip build artifacts + nested target dirs (rust-analyzer makes them)
        if matches!(
            name_str.as_ref(),
            "target" | "dist" | ".git" | "Cargo.lock" | "node_modules" | "data"
        ) {
            continue;
        }
        if name_str == ".DS_Store" {
            continue;
        }

        let src_path = entry.path();
        let dst_path = dst.join(&name);

        if entry.file_type().expect("file type").is_dir() {
            copy_filtered(&src_path, &dst_path);
        } else {
            std::fs::copy(&src_path, &dst_path).expect("file copy");
        }
    }
}
